### ISSUE TITLE
Chrome extension version 24.6.30 requesting permission to "Read and change all your data on all websites"

### ISSUE THREAD

**Issue by ezzatron** [notlmn/copy-as-markdown#49]
<img width="321" alt="Screenshot 2024-07-02 at 17 21 16" src="https://github.com/notlmn/copy-as-markdown/assets/100152/61988d5b-43c5-4693-81e6-4eb883865925">

Seems like a mistake?

**Comment by tonytamps** [comment]
I'm extremely suspicious about this new permission. I can't see how the recent changes have caused the request for the new permission and it gives me concern that the extension source does not represent the distributed extension.

This is probably just a mistake, and notlmn does a good job of being transparent regarding deployments, but until this is explained I have uninstalled it. The supply chain could be compromised.

**Comment by notlmn** [comment]
Distribution happens once every week, the source might be different from when the release has happened if you are looking at the main branch of the repo. If you look at the commits for the tag `24.6.24`, you'll see what the mistake was.

I have been trying to push for newer release as Firefox releases are almost instant, but Chrome release need manual review from CWS side which is why the releases are still off between these two platforms.

It is fair to suspect the botched releases until then, you don't have to take my word for it. Meanwhile anyone can download the published extension manually and inspect the code to confirm that's there's nothing malicious in there.

Please wait until `24.7.1` (still under review) to be release onto Chrome Webstore that should not have this problem.

**Comment by notlmn** [comment]
For anyone following, the fix was already sent out in  #47, but waiting for the CWS release.

**Comment by tonytamps** [comment]
Thanks for the pointer to checkout that tag. That makes sense 🙇 Much appreciated.

**Comment by notlmn** [comment]
This should be fixed.

**Comment by johnmellor** [comment]
Thanks but this isn't fixed yet. Version 25.6.9 (updated 11 June 2025) still asks for "Read and change all your data on all websites" when you try to install it. It's been that way ever since #44 added the following to manifest.json:

```json
"content_scripts": [
	{
		"matches": ["*://*/*"],
		"js": ["copy-as-markdown.js"],
		"run_at": "document_start"
	}
  ],
```

which injects JS into every web page the user visits. You could avoid the scary permission by instead [injecting it programmatically](https://developer.chrome.com/docs/extensions/develop/concepts/content-scripts#programmatic) using the `activeTab` permission only when the context menu is invoked.

**Comment by tonytamps** [comment]
Honestly @johnmellor - I would probably look for a different ext or fork and install as a dev dependency. The permission issues have gone on too long for trust to be maintained in the repo going forward.
